Areas/ProductManage/Models/ProductModel.cs
namespace App.Models
{
    public class ProductModel
    {

        public int Id { set; get; }
        public string Name { set; get; }
        public int Price { set; get; }
    }
}

Models/AppDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace App.Models
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
        {

        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
        }

        public DbSet<ProductModel> products { set; get; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace App.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PlanetModel.cs
namespace App.Models
{
    public class PlanetModel
    {
        public int Id { set; get; }
        public string Name { set; get; }
        public string VnName { set; get; }
        public string Content { set; get; }
    }
}

Areas/ProductManage/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using App.Models;
using App.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace App.Controllers
{
    [Area("ProductManage")]
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;
        private readonly ProductInitService _productService;
        [TempData]
        public string StatusMessage { set; get; }
        public ProductController(ILogger<ProductController> logger, ProductInitService productService)
        {
            _logger = logger;
            _productService = productService;
        }
        public IActionResult Index()
        {
            var products = _productService.ToList();
            return View(products);
        }
        public IActionResult Detail(int? id)
        {
            if (id == null) return NotFound($"Can not find product has Id = {id}");
            var product = _productService.Where(p => p.Id == id).FirstOrDefault();
            if (product == null)
            {
                StatusMessage = $"Can not find product has id = {id}";
                return Redirect("/Product/Index");
            }
            return View(product);
        }
    }
}

Controllers/HomeController.cs
using System.IO;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using App.Models;

namespace App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Bird()
        {
            string filePath = Path.Combine(Startup.ContentRootPath, "Files", "Bird.jpg");
            var bytes = System.IO.File.ReadAllBytes(filePath);

            return File(bytes, "image/jpg");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PlanetController.cs
using System;
using App.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Linq;

namespace App.Controllers
{
    public class PlanetController : Controller
    {
        private readonly ILogger<PlanetController> _logger;
        private readonly PlanetService _planetService;

        public PlanetController(ILogger<PlanetController> logger, PlanetService planetService)
        {
            _logger = logger;
            _planetService = planetService;
        }

        public IActionResult Index()
        {
            var planets = _planetService.ToList();

            return View(planets);
        }
        public IActionResult Mercury()
        {
            var planet = _planetService.Where(p => p.Name == "Mercury").FirstOrDefault();
            if (planet == null)
            {
                return Content("Can not find planet Mercury");
            }

            return View("Detail", planet);
        }

        public IActionResult Venus()
        {
            var planet = _planetService.Where(p => p.Name == "Venus").FirstOrDefault();
            if (planet == null)
            {
                return Content("Can not find planet Venus");
            }

            return View("Detail", planet);
        }

        public IActionResult Mars()
        {
            var planet = _planetService.Where(p => p.Name == "Mars").FirstOrDefault();
            if (planet == null)
            {
                return Content("Can not find planet Mars");
            }

            return View("Detail", planet);
        }

        public IActionResult Earth()
        {
            var planet = _planetService.Where(p => p.Name == "Earth").FirstOrDefault();
            if (planet == null)
            {
                return Content("Can not find planet Earth");
            }

            return View("Detail", planet);
        }
    }
}

Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using App.Models;
using App.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace App.Controllers
{
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;
        private readonly ProductInitService _productService;
        [TempData]
        public string StatusMessage { set; get; }
        public ProductController(ILogger<ProductController> logger, ProductInitService productService)
        {
            _logger = logger;
            _productService = productService;
        }
        public IActionResult Index()
        {
            var products = _productService.ToList();
            return View(products);
        }
        public IActionResult Detail(int? id)
        {
            if (id == null) return NotFound($"Can not find product has Id = {id}");
            var product = _productService.Where(p => p.Id == id).FirstOrDefault();
            if (product == null)
            {
                StatusMessage = $"Can not find product has id = {id}";
                return Redirect("/Product/Index");
            }
            return View(product);
        }
    }
}

Areas/Database/Views/DbManage/Delete.cshtml
@{
    ViewData["Title"] = "Delete Database";
}

<h2>@ViewData["Title"]</h2>

<hr>

<div class="alert alert-danger">
    <p>Are you sure to delete database ?</p>
</div>

<form method="post">
    <button asp-area="Database" asp-action="Delete" class="btn btn-danger" type="submit">Delete</button>
    <a asp-action="Index" asp-area="Database" class="btn btn-secondary">Back</a>
</form>

Areas/Database/Views/DbManage/Index.cshtml
@using Microsoft.EntityFrameworkCore
@{
    ViewData["Title"] = "Database Manage";
}

@inject AppDbContext dbContext

<h2>@ViewData["Title"]</h2>

<partial name="_StatusMessage" />

<hr>
<h4>Database Information</h4>
@{
    var connect = dbContext.Database.GetDbConnection();
    var dbname = connect.Database;
    var can_connect = dbContext.Database.CanConnect();
}

<p>Database: @dbname</p>
<p>Data Source: @connect.DataSource</p>
<p>State: @connect.State</p>

<h4>Migration List</h4>
@if (dbContext.Database.GetAppliedMigrations().Any())
{
    var migrations = dbContext.Database.GetAppliedMigrations();
    @foreach (var migration in migrations)
    {
        <div class="list-group">
            <p class="list-group-item">@migration</p>
        </div>
    }
}

@if (dbContext.Database.GetPendingMigrations().Any())
{
    var migrations = dbContext.Database.GetPendingMigrations();
    @foreach (var migration in migrations)
    {
        <div class="list-group">
            <p class="list-group-item">@(migration) (Pending)</p>
        </div>
    }
}

@if (!can_connect)
{
    <div class="alert alert-danger">
        <p>Can not connect to database</p>
    </div>
}

@if (can_connect)
{
    await dbContext.Database.OpenConnectionAsync();
    var table = dbContext.Database.GetDbConnection().GetSchema("Tables");
    <h4>Table list</h4>
    @foreach (System.Data.DataRow row in table.Rows)
    {
        <li>@row["TABLE_NAME"]</li>
    }

    <div class="mt-2">
        <a class="btn btn-danger" asp-action="Delete" asp-area="Database">Delete Database </a>
    </div>
}

@if (dbContext.Database.GetPendingMigrations().Any())
{
    <a class="btn btn-primary" asp-action="Migrate" asp-area="Database">Create Database(Migrate)</a>

}

Areas/ProductManage/Views/Product/Detail.cshtml
@{
    ViewData["Title"] = "View Detail Product";
}
@model App.Models.ProductModel

<h2>@ViewData["Title"]</h2>
<hr>

<div class="row">
    <div class="col-sm-6">
        <div class="alert alert-success card">
            <div class="card-header font-weight-bold text-center">
                <h2>@Model.Name</h2>
            </div>
            <div class="card-body">
                <div class="card-text text-mute">Price: @Model.Price</div>
            </div>
        </div>
    </div>
</div>

<a asp-controller="Product" asp-action="Index" class="btn btn-secondary">List Product</a>

Areas/ProductManage/Views/Product/Index.cshtml
@model List<App.Models.ProductModel>
@{
    ViewData["Title"] = "Product List";
    var products = Model as List<ProductModel>;
    var StatusMessage = TempData["StatusMessage"] as string;
}
<h2>@ViewData["Title"]</h2>
<partial name="_StatusMessage" model="StatusMessage" />
@if (Model.Count > 0)
{
    <ul>
        @foreach (var product in products)
        {
            <li><a asp-controller="Product" asp-action="Detail" asp-area="ProductManage"
            asp-route-id="@product.Id">@product.Name - @product.Price</a>
            </li>
        }
    </ul>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Planet/Detail.cshtml
@model App.Models.PlanetModel
@{
    ViewData["Title"] = Model.Name;
}

<a asp-action="Index" class="btn btn-primary">Back</a>

<h2>@ViewData["Title"]</h2>
<hr>
<div class="card" style="width: 25rem;">
    <img src="~/image/@(Model.Name).jpg" alt="@Model.Name" class="card-img-top">
    <div class="card-body">
        <h5 class="card-title">@Model.VnName</h5>
        <p class="card-text">@Model.Content</p>
    </div>
    <div class="card-footer">
        <a asp-action="Index">List Planet</a>
    </div>
</div>

Views/Planet/Index.cshtml
@model List<App.Models.PlanetModel>
@{
    ViewData["Title"] = "List planet in solar system";
    var planets = Model;
}

<h2>@ViewData["Title"]</h2>
<hr />

@if (planets != null)
{
    <div class="list-group">
        @foreach(var planet in planets)
        {
            <a class="list-group-item" asp-action="@planet.Name">@planet.Name - @planet.VnName</a>
        }
    </div>
}

Views/Product/Index.cshtml
@model List<App.Models.ProductModel>
@{
    ViewData["Title"] = "Product List";
    var products = Model as List<ProductModel>;
    var StatusMessage = TempData["StatusMessage"] as string;
}
<h2>@ViewData["Title"]</h2>
<partial name="_StatusMessage" model="StatusMessage" />
@if (Model.Count > 0)
{
    <ul>
        @foreach (var product in products)
        {
            <li><a asp-controller="Product" asp-action="Detail" asp-route-id="@product.Id">@product.Name - @product.Price</a>
            </li>
        }
    </ul>
}

Views/Shared/_DbManage.cshtml
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown">
        Database
    </a>
    <div class="dropdown-menu">
        <a class="dropdown-item" asp-action="Index" asp-controller="DbManage" asp-area="Database">Database</a>
    </div>
</li>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC Web App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC Web App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Planet"
                                asp-action="Index">Planet</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        <partial name="_DbManage" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVC_01_MVCArchitecture - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Views/Shared/_StatusMessage.cshtml
@model string

@{
    var message = TempData["StatusMessage"];
}

@if (message != null)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        @message
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}